Add `starts_with` and `convert_prefix`
oNaiPs/secrets-to-env-action pull request #110
Opened 2022-11-15 11:54 UTC by KTamas

We needed a way to pull down `n` secrets to the environment that has a common prefix, so I added that feature as well as another one that does not apply string conversions on said prefix. So the secret `TF_VAR_AWS_ACCESS_KEY` becomes `TF_VAR_aws_access_key` and so on.

I've also updated to the latest versions of dependencies.

2022-11-16 11:34 UTC, oNaiPs requested changes
Many thanks for your contribution! Please check the comments I left, and:
- Please remove the distribution files, I will generate them after the PR is merged

2022-11-16 11:34 UTC, oNaiPs commented on README.md
> +  <a href="https://github.com/compasspathways/secrets-to-env-action/actions"><img alt="secrets-to-env-action status" src="https://github.com/compasspathways/secrets-to-env-action/workflows/build-test
Please update back to original

2022-11-16 11:34 UTC, oNaiPs commented on package.json
> +    "@actions/core": "^1.10.0",
Remove dependency updates from this PR

2023-02-05 11:19 UTC, oNaiPs commented
Integrated into `main`. Thanks!

2023-02-05 11:19 UTC, closed without merging

2023-02-05 12:20 UTC, KTamas commented
Thanks, apologies for not getting around to make the proposed changes.