Added option to convert secrets to base64
oNaiPs/secrets-to-env-action pull request #303
Opened 2024-03-12 11:56 UTC by danilokorber

**Converts all exported secrets to a base64 string (default is false):**

```yaml
steps:
- uses: actions/checkout@v3
- uses: oNaiPs/secrets-to-env-action@v1
  with:
    secrets: ${{ toJSON(secrets) }}
    value_as_base64: true
- run: echo "Value of my_secret: $my_secret"
```

If `value_as_base64` is true, the value of the secret will be converted to a base64 string.

2024-03-12 12:32 UTC, oNaiPs requested changes
@danilokorber thanks for the PR.
Since we already have an attribute `convert` that allows you to convert the inputs, let's use `convert: base64` instead to achieve your goal?
Thanks

2024-03-12 13:00 UTC, danilokorber commented
> @danilokorber thanks for the PR. Since we already have an attribute `convert` that allows you to convert the inputs, let's use `convert: base64` instead to achieve your goal? Thanks

Hey @oNaiPs 
I thought of using the `convert` attribute, but I thought this could be confusing, since `convert` is used to change the key and this PR is to change the value. Additionaly, this allows us to change the key to the desired form AND the value to base64.

2024-03-12 13:07 UTC, danilokorber commented on src/main.ts
> +      let newValue = valueAsBase64 ? encode(secrets[key]) : secrets[key]
Fixed.

2025-12-21 17:15 UTC, oNaiPs commented
@danilokorber apologies for not having followed up on this yet. I like your suggestiong about `convert_value`. Let's go with it?
Also please revert the metadata changes.

Thanks

2026-03-12 19:53 UTC, oNaiPs commented
Hi @danilokorber, thanks for taking the time to contribute!

After reviewing this, I've decided not to merge it. Base64 encoding can be easily achieved in workflow steps themselves (e.g. `echo -n "$MY_SECRET" | base64`), so adding a dedicated flag for it introduces maintenance overhead without much added value — especially since it applies to all secrets at once with no per-secret control.

There are also a few issues with the PR itself (authorship changes in action.yml, missing dist rebuild, typo), but the main reason is that this falls outside the scope I'd like to keep for this action.

Appreciate the effort nonetheless!

2026-03-12 19:53 UTC, closed without merging